"""
============================================================
InsightForge Sentinel
Validation Engine
============================================================

Purpose:
    Executes an execution plan generated by the Rule Engine
    by delegating validation to specialized validators.

Author : InsightForge
Version : 3.0
"""

from models.validation_result import ValidationResult
from rules.validation.validator_registry import ValidatorRegistry


class ValidationEngine:

    def __init__(self):

        self.registry = ValidatorRegistry()

    # ======================================================

    def run(
        self,
        dataframe,
        knowledge,
        execution_plan
    ):

        results = []

        passed = 0
        failed = 0
        not_implemented = 0

        for task in execution_plan:

            result = self._execute_task(
                dataframe,
                knowledge,
                task
            )

            results.append(result)

            if result.status == "PASS":

                passed += 1

            elif result.status == "FAIL":

                failed += 1

            else:

                not_implemented += 1

        return {

            "engine": "ValidationEngine",

            "status": "SUCCESS",

            "rules_executed": len(results),

            "passed": passed,

            "failed": failed,

            "not_implemented": not_implemented,

            "results": results

        }

    # ======================================================

    def _execute_task(
        self,
        dataframe,
        knowledge,
        task
    ):

        validation = task.rule.validation.upper()

        validator = self.registry.get(validation)

        if validator is None:

            return ValidationResult(

                rule_id=task.rule.rule_id,

                rule_name=task.rule.name,

                column=task.column,

                business_type=task.business_type,

                validation=validation,

                severity=task.rule.severity,

                status="NOT_IMPLEMENTED",

                message=f"No validator registered for '{validation}'.",

                recommendation=task.rule.recommendation,

                business_impact=task.rule.business_impact

            )

        return validator.validate(
            dataframe,
            knowledge,
            task
        )